all: hello_server hello_client

hello_server: hello_server.c
	gcc -o hello_server hello_server.c

hello_client: hello_client.c
	gcc -o hello_client hello_client.c

clean:
	rm -rf hello_server hello_client
